version: "3.8"

services:
  backend:
    build:
      context: ./web-socket-chat-app-backend
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
    networks:
      - chat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./web-socket-chat-app-frontend
    container_name: chat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge
