version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - chat-network

  backend:
    build:
      context: ./web-socket-chat-app-backend
    container_name: chat-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq
    networks:
      - chat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./web-socket-chat-app-frontend
    container_name: chat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge
